### ISSUE TITLE
No module named cli.colors

### ISSUE THREAD

**Issue by dmitrybelyakov** [projectshift/shift-boiler#19]
Unable to install:

```
Traceback (most recent call last):
  File "/usr/local/bin/boiler", line 7, in <module>
    from boiler.cli.boiler import cli
  File "/usr/local/lib/python2.7/site-packages/boiler/cli/boiler.py", line 2, in <module>
    from boiler.cli.colors import *
ImportError: No module named cli.colors
```

**Comment by dmitrybelyakov** [comment]
Does not work when there's a global boiler install
